/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindDoctorsRouteImport } from './routes/find-doctors'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientSavedRouteImport } from './routes/patient.saved'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientRecordsRouteImport } from './routes/patient.records'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as PatientArticlesRouteImport } from './routes/patient.articles'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientAiRouteImport } from './routes/patient.ai'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorReviewsRouteImport } from './routes/doctor.reviews'
import { Route as DoctorRecordsRouteImport } from './routes/doctor.records'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor.availability'
import { Route as DoctorArticlesRouteImport } from './routes/doctor.articles'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminHospitalsRouteImport } from './routes/admin.hospitals'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAiAnalyticsRouteImport } from './routes/admin.ai-analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDoctorsRoute = FindDoctorsRouteImport.update({
  id: '/find-doctors',
  path: '/find-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSavedRoute = PatientSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientRecordsRoute = PatientRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PatientRoute,
} as any)
const PatientArticlesRoute = PatientArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAiRoute = PatientAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorReviewsRoute = DoctorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorRecordsRoute = DoctorRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorArticlesRoute = DoctorArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHospitalsRoute = AdminHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAnalyticsRoute = AdminAiAnalyticsRouteImport.update({
  id: '/ai-analytics',
  path: '/ai-analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/find-doctors': typeof FindDoctorsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/ai-analytics': typeof AdminAiAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/articles': typeof DoctorArticlesRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/patient/ai': typeof PatientAiRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/articles': typeof PatientArticlesRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/saved': typeof PatientSavedRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/contact': typeof ContactRoute
  '/find-doctors': typeof FindDoctorsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/ai-analytics': typeof AdminAiAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/articles': typeof DoctorArticlesRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/patient/ai': typeof PatientAiRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/articles': typeof PatientArticlesRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/saved': typeof PatientSavedRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/find-doctors': typeof FindDoctorsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/ai-analytics': typeof AdminAiAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/articles': typeof DoctorArticlesRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/records': typeof DoctorRecordsRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/patient/ai': typeof PatientAiRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/articles': typeof PatientArticlesRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/saved': typeof PatientSavedRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/articles'
    | '/contact'
    | '/doctor'
    | '/find-doctors'
    | '/login'
    | '/patient'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/admin/ai-analytics'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/articles/$id'
    | '/doctor/appointments'
    | '/doctor/articles'
    | '/doctor/availability'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/records'
    | '/doctor/reviews'
    | '/doctor/settings'
    | '/doctors/$id'
    | '/patient/ai'
    | '/patient/appointments'
    | '/patient/articles'
    | '/patient/book'
    | '/patient/doctors'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/records'
    | '/patient/reports'
    | '/patient/saved'
    | '/patient/settings'
    | '/admin/'
    | '/articles/'
    | '/doctor/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-assistant'
    | '/contact'
    | '/find-doctors'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/admin/ai-analytics'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/articles/$id'
    | '/doctor/appointments'
    | '/doctor/articles'
    | '/doctor/availability'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/records'
    | '/doctor/reviews'
    | '/doctor/settings'
    | '/doctors/$id'
    | '/patient/ai'
    | '/patient/appointments'
    | '/patient/articles'
    | '/patient/book'
    | '/patient/doctors'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/records'
    | '/patient/reports'
    | '/patient/saved'
    | '/patient/settings'
    | '/admin'
    | '/articles'
    | '/doctor'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-assistant'
    | '/articles'
    | '/contact'
    | '/doctor'
    | '/find-doctors'
    | '/login'
    | '/patient'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/admin/ai-analytics'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/articles/$id'
    | '/doctor/appointments'
    | '/doctor/articles'
    | '/doctor/availability'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/records'
    | '/doctor/reviews'
    | '/doctor/settings'
    | '/doctors/$id'
    | '/patient/ai'
    | '/patient/appointments'
    | '/patient/articles'
    | '/patient/book'
    | '/patient/doctors'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/records'
    | '/patient/reports'
    | '/patient/saved'
    | '/patient/settings'
    | '/admin/'
    | '/articles/'
    | '/doctor/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  FindDoctorsRoute: typeof FindDoctorsRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-doctors': {
      id: '/find-doctors'
      path: '/find-doctors'
      fullPath: '/find-doctors'
      preLoaderRoute: typeof FindDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/saved': {
      id: '/patient/saved'
      path: '/saved'
      fullPath: '/patient/saved'
      preLoaderRoute: typeof PatientSavedRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/records': {
      id: '/patient/records'
      path: '/records'
      fullPath: '/patient/records'
      preLoaderRoute: typeof PatientRecordsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/articles': {
      id: '/patient/articles'
      path: '/articles'
      fullPath: '/patient/articles'
      preLoaderRoute: typeof PatientArticlesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/ai': {
      id: '/patient/ai'
      path: '/ai'
      fullPath: '/patient/ai'
      preLoaderRoute: typeof PatientAiRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/reviews': {
      id: '/doctor/reviews'
      path: '/reviews'
      fullPath: '/doctor/reviews'
      preLoaderRoute: typeof DoctorReviewsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/records': {
      id: '/doctor/records'
      path: '/records'
      fullPath: '/doctor/records'
      preLoaderRoute: typeof DoctorRecordsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/availability': {
      id: '/doctor/availability'
      path: '/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/articles': {
      id: '/doctor/articles'
      path: '/articles'
      fullPath: '/doctor/articles'
      preLoaderRoute: typeof DoctorArticlesRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hospitals': {
      id: '/admin/hospitals'
      path: '/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AdminHospitalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-analytics': {
      id: '/admin/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/admin/ai-analytics'
      preLoaderRoute: typeof AdminAiAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiAnalyticsRoute: typeof AdminAiAnalyticsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminHospitalsRoute: typeof AdminHospitalsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiAnalyticsRoute: AdminAiAnalyticsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminHospitalsRoute: AdminHospitalsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesIdRoute: typeof ArticlesIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesIdRoute: ArticlesIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorArticlesRoute: typeof DoctorArticlesRoute
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorRecordsRoute: typeof DoctorRecordsRoute
  DoctorReviewsRoute: typeof DoctorReviewsRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorArticlesRoute: DoctorArticlesRoute,
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorRecordsRoute: DoctorRecordsRoute,
  DoctorReviewsRoute: DoctorReviewsRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientAiRoute: typeof PatientAiRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientArticlesRoute: typeof PatientArticlesRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientDoctorsRoute: typeof PatientDoctorsRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientRecordsRoute: typeof PatientRecordsRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientSavedRoute: typeof PatientSavedRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAiRoute: PatientAiRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientArticlesRoute: PatientArticlesRoute,
  PatientBookRoute: PatientBookRoute,
  PatientDoctorsRoute: PatientDoctorsRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientRecordsRoute: PatientRecordsRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientSavedRoute: PatientSavedRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ContactRoute: ContactRoute,
  DoctorRoute: DoctorRouteWithChildren,
  FindDoctorsRoute: FindDoctorsRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  DoctorsIdRoute: DoctorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
